### ISSUE TITLE
dead link in readme: gather-based warping ref

### ISSUE THREAD

**Issue by ChristophHaag** [a2flo/floor_examples#2]
> gather-based warping ref: http://www.cs.virginia.edu/~gfx/pmwiki/index.php?n=Pubs.Yang2011IBB

> Not Found
> The requested URL /~gfx/pmwiki/index.php was not found on this server.

**Comment by tohn** [comment]
maybe you could link to [the archive](https://web.archive.org/web/20170611112307/http://www.cs.virginia.edu:80/~gfx/pmwiki/index.php?n=Pubs.Yang2011IBB)?

**Comment by a2flo** [comment]
Thanks, I replaced it with a link to a copy from one of the other authors + added the archive link in case this may be useful.
